import type { SpiritAnimal, SpiritEffects, SpiritManifestation } from "../Spirits";
import type { Language } from "./Labels";

type UILabels =
    | 'label:spirit_animal'
    | 'label:spirit_manifestation'
    | 'label:spirit_effect'

export const SpiritLabels: Record<Language, Record<SpiritEffects | SpiritAnimal | SpiritManifestation | UILabels, string>> = {
    en: {
        "effect:land_on_feet": 'You always land on your feet, no matter how high you fall from',
        'effect:resist_normal_cold': 'You never feel cold in non-magical cold',
        'effect:see_in_dark': 'You can see in the dark',
        'effect:tree_climbing': 'You can climb trees and poles as fast as you can walk',
        'effect:exceptional_smell': 'You have an exceptional sense of smell',
        'effect:hibernation': '1-2 days of continuous sleep will rid you of all poisons or disease',
        'effect:intimidating_presence': 'Your appearance discourages strangers from angering you',
        'effect:friend_shaped': 'You are friend shaped: you appear cute or harmless regardless of the reality',
        'effect:detect_spirits': 'You can feel the presence of spirits in a place',
        'effect:wriggle_free': 'Given enough time, you can wriggle free of any hold, bond or rope',
        'effect:exceptional_hearing': 'You have exceptional hearing',
        'effect:follow_tracks': 'You can step precisely into an existing set of footprints, leaving no track of your own',
        'effect:circular_vision': `You can see everything around you, you can't be stalked except from directly above or below`,
        'effect:zigzagging': 'You can run at full speed in a zig-zag pattern, confusing pursuers or anyone trying to aim at you',
        'effect:glide': 'When you jump downwards, you can travel twice as far horizontally as vertically',
        'effect:messenger': 'Spells that send messages have an infinite range when cast by or targeting you',
        'effect:insatiable': 'You can eat or drink anyone under the table',
        'effect:exceptional_swimmer': 'You can carry as much gear while swimming as on land',
        'effect:poison_immune': 'You are immune to all poisons',
        'effect:pack_fighter': 'Whenever a friend in your vicinity is attacked, you can semse it and instantly appear on their side to fight back',
        'effect:gambler': 'Whenever you need to roll dice to determine success at gambling, roll them twice and pick the better result',
        'effect:gorge': 'You can eat prodigious amounts of food: in a single sitting you can eat enough to keep you going for three days',
        'effect:mask_party_size': 'You can make your group appear up to twice or down to half the size, at least from a distance or when being tracked',
        'effect:sense_friends': 'You always know how far and in which direction all the members of your group are',
        'effect:sense_disturbance': 'You can sense when something is not quite right with any member of your group, be it poisoning, illness or influence by magic or spirits',
        'effect:mimicry': 'You can mimic anyone\'s voice after you heard them speaking',
        'effect:subitise': 'You can accurately count things at a single glance: like how many coins are in a pile or people in a hall',
        'effect:weapon_return': 'Your thrown weapons return to your hand if they miss',
        'effect:resist_normal_heat': 'You never feel too hot in non-magical heat',
        'effect:sense_movement': 'Your vision is not only more acute than usual, it is extra sensitive to movement. It is impossible to stalk you unless it\'s outside your field of vision',
        'effect:powerful_bite': 'You can bite branches or wooden hafts of no more than two inches in diameter in half. (To use this in combat you need to be in close quarters and roll a successful unarmed attack roll first.)',
        'manifestation:bear:paws': `Bear's paws`,
        'manifestation:bear:fur': `Bear's fur`,
        'manifestation:bear:nose': `Bear's nose`,
        'manifestation:bear:sleep': `Bear's sleep`,
        'manifestation:bear:visage': `Bear's visage`,
        'manifestation:bear:fangs': `Bear's fangs`,
        'manifestation:cat:paws': `Cat's paws`,
        'manifestation:cat:eyes': `Cat's eyes`,
        'manifestation:cat:whiskers': `Cat's whiskers`,
        'manifestation:cat:dexterity': `Cat's dexterity`,
        'manifestation:cat:ears': `Cat's ears`,
        'manifestation:cat:tail': `Cat's tail`,
        'manifestation:squirrel:eyes': `Squirrel's eyes`,
        'manifestation:squirrel:legs': `Squirrel's legs`,
        'manifestation:squirrel:paws': `Squirrel's paws`,
        'manifestation:squirrel:tail': `Squirrel's tail`,
        'manifestation:squirrel:ears': `Squirrel's ears`,
        'manifestation:squirrel:fur': `Squirrel's fur`,
        'manifestation:boar:tusks': `Boar's tusks`,
        'manifestation:boar:appetite': `Boar's appetite`,
        'manifestation:boar:strength': `Boar's strength`,
        'manifestation:boar:nerves': `Boar's nerves`,
        'manifestation:boar:courage': `Boar's courage`,
        'manifestation:boar:luck': `Boar's luck`,
        'manifestation:wolf:eyes': `Wolf's eyes`,
        'manifestation:wolf:feet': `Wolf's feet`,
        'manifestation:wolf:heart': `Wolf's heart`,
        'manifestation:wolf:howl': `Wolf's howl`,
        'manifestation:wolf:hunger': `Wolf's hungar`,
        'manifestation:wolf:nose': `Wolf's nose`,
        'manifestation:parrot:beak': `Parrot's beak`,
        'manifestation:parrot:brain': `Parrot's brain`,
        'manifestation:parrot:eye': `Parrot's eye`,
        'manifestation:parrot:feather': `Parrot's feather`,
        'manifestation:parrot:voice': `Parrot's voice`,
        'manifestation:parrot:wing': `Parrot's wing`,
        'spirit:bear': 'Bear',
        'spirit:cat': 'Cat',
        'spirit:squirrel': 'Squirrel',
        'spirit:boar': 'Boar',
        'spirit:wolf': 'Wolf',
        'spirit:parrot': 'Parrot',
        'label:spirit_animal': 'Spirit Animal',
        'label:spirit_manifestation': 'Manifestation',
        'label:spirit_effect': 'Effect',
    },
    hu: {
        "effect:land_on_feet": 'Akármilyen magasról esel, mindig talpra érkezel',
        'effect:resist_normal_cold': 'Sosem fázol nem mágikus hidegben',
        'effect:see_in_dark': 'Látsz a sötétben',
        'effect:tree_climbing': 'Olyan gyorsan tudsz fára mászni, mint ahogy gyalogolni',
        'effect:exceptional_smell': 'A szaglásod kiemelkedő',
        'effect:hibernation': '1-2 napnyi folyamatos alvással megszabadulsz minden betegségtől vagy mérgezéstől',
        'effect:intimidating_presence': 'A megjelenésed azt sugallja, hogy nem jó ötlet téged felbosszantani',
        'effect:friend_shaped': 'Barátformád van, cukinak és ártalmatlannak tűnsz függetlenül a valóságtól',
        'effect:detect_spirits': 'Érzékeled egy hely szellemeinek jelenlétét',
        'effect:wriggle_free': 'Elegendő idő alatt bármilyen fogásból, bilincsből vagy kötelékből ki tudsz szabadulni segítség nélkül',
        'effect:exceptional_hearing': 'A hallásod kiemelkedő',
        'effect:follow_tracks': 'Képes vagy pontosan egy már meglevő lábnyomba lépni, nem hagyva magad után sajátot',
        'effect:circular_vision': `Mindent látsz magad körül, képtelenség téged becserkészni, kivéve teljesen felülről vagy alulról`,
        'effect:zigzagging': 'Teljes sebességgel tudsz cikkcakkban szaladni, összezavarva üldözőidet vagy bárkit, aki célozni próbál rád',
        'effect:glide': 'Amikor lefele ugrasz, kétszer olyan messzire tudsz eljutni vízszintesen, mint függőlegesen',
        'effect:messenger': 'Az általad vagy rád varázsolt üzenetküldő varázslatok hatótávja végtelen',
        'effect:insatiable': 'Bárkit az asztal alá tudsz enni vagy inni',
        'effect:exceptional_swimmer': 'Annyi felszereléssel tudsz úszni, amennyit gyalog elbírsz',
        'effect:poison_immune': 'Minden méregre immunis vagy',
        'effect:pack_fighter': 'Amikor bármely társadat megtámadják a közeledben, azonnal érzékeled és mellette tudsz teremni harcra készen',
        'effect:gambler': 'Bármely kockadobást, amely szerencsejáték kimenetelét határozza meg, kétszer dobhatsz és válaszd a kedvezőbbet.',
        'effect:gorge': 'Legendás mennyiségű ételt tudsz magadba tömni, egy étkezés során akár három napra elegendőt is',
        'effect:mask_party_size': 'Csapatodat akár kétszer- vagy feleakkorának is álcázhatod, legalábbis ha valaki csak távolról érzékel titeket vagy a nyomaitokat követi',
        'effect:sense_friends': 'Mindig tudod, hogy a csapatod többi tagja milyen messze és milyen irányban tartózkodik',
        'effect:sense_disturbance': 'Érzed, ha valami nem stimmel a csapatod bármely tagjával, legyen az mérgezés, betegség, esetleg mágikus vagy szellem általi befolyás',
        'effect:mimicry': 'Bárkinek a hangját tudod utánozni, ha már hallottad beszélni',
        'effect:subitise': 'Egyetlen pillantással meg tudod számolni az előtted levő dolgokat: pl. hány érme van egy halomban vagy hány ember egy teremben',
        'effect:weapon_return': 'A dobófegyvereid visszatérnek a kezedbe, ha nem találnak',
        'effect:resist_normal_heat': 'Sosincs meleged nem mágikus melegben',
        'effect:sense_movement': 'Látásod nemcsak élesebb a szokásosnál, a mozgásra különösképp érzékeny, így lehetetlen téged lopakodással meglepni, hacsak nem hátulról közelítenek',
        'effect:powerful_bite': 'Kétujjnyinál nem vastagabb fa rudakat vagy ágakat egy mozdulattal ketté tudsz harapni (harcban csak akkor alkalmazható, ha belharcban vagy az ellenfeleddel és sikeres pusztakezes támadódobást dobsz)',
        'manifestation:bear:paws': `Medvemancs`,
        'manifestation:bear:fur': `Medveszőr`,
        'manifestation:bear:nose': `Medveorr`,
        'manifestation:bear:sleep': `Medveálom`,
        'manifestation:bear:visage': `Medvepofi`,
        'manifestation:bear:fangs': `Medveagyar`,
        'manifestation:cat:paws': `Macskamancs`,
        'manifestation:cat:eyes': `Macskaszem`,
        'manifestation:cat:whiskers': `Macskabajusz`,
        'manifestation:cat:dexterity': 'Macskaügyesség',
        'manifestation:cat:ears': 'Macskafül',
        'manifestation:cat:tail': 'Macskafarok',
        'manifestation:squirrel:eyes': 'Mókusszem',
        'manifestation:squirrel:legs': 'Mókusláb',
        'manifestation:squirrel:paws': 'Mókusmancs',
        'manifestation:squirrel:tail': `Mókusfarok`,
        'manifestation:squirrel:ears': 'Mókusfül',
        'manifestation:squirrel:fur': `Mókusszőr`,
        'manifestation:boar:tusks': `Vadkanagyar`,
        'manifestation:boar:appetite': 'Vadkanétvágy',
        'manifestation:boar:strength': 'Vadkanerő',
        'manifestation:boar:nerves': 'Vadkanideg',
        'manifestation:boar:courage': 'Vadkanbátorság',
        'manifestation:boar:luck': 'Vadkanszerencse',
        'manifestation:wolf:eyes': `Farkasszem`,
        'manifestation:wolf:feet': `Farkasláb`,
        'manifestation:wolf:heart': `Farkasszív`,
        'manifestation:wolf:howl': `Farkasvonyítás`,
        'manifestation:wolf:hunger': `Farkaséhség`,
        'manifestation:wolf:nose': `Farkasorr`,
        'manifestation:parrot:beak': `Papagájcsőr`,
        'manifestation:parrot:brain': `Papagájagy`,
        'manifestation:parrot:eye': `Papagájszem`,
        'manifestation:parrot:feather': `Papagájtoll`,
        'manifestation:parrot:voice': `Papagájhang`,
        'manifestation:parrot:wing': `Papagájszárny`,
        'spirit:bear': 'Medve',
        'spirit:cat': 'Macska',
        'spirit:squirrel': 'Mókus',
        'spirit:boar': 'Vadkan',
        'spirit:wolf': 'Farkas',
        'spirit:parrot': 'Papagáj',
        'label:spirit_animal': 'Totemállat',
        'label:spirit_manifestation': 'Megnyilvánulás',
        'label:spirit_effect': 'Hatás',
    }
}