export type BoxFlavour = | 'character-sheet'
    | 'character'
    | 'abilities'
    | 'skills'
    | 'points'
    | 'inventory'
    | 'action-container'
    | 'action-card'
    | 'action-distance'
    | 'action-variant-selectable'
    | 'action-variant-unselectable'
    | 'action-variant-selected'
    | 'lore'
    | 'simulator-life'
    | 'simulator-turns'
    | 'plain';